### ISSUE TITLE
Found differences between the code in github and the official(?) site

### ISSUE THREAD

**Issue by 30stm** [andreww/fox#46]
Hi 
I found same version codes (4.1.2) in this github and the link below
http://homepages.see.leeds.ac.uk/~earawa/FoX/source/

and I also found the codes named same version are different in some f90 files.
Maybe you modified some parts, which one is more recent and compact?
In addition, FoX from the link even does not have test codes about DOM api and 
the test codes about SAX api did not work because of "len(attributes)" in m_handler

I'll be waiting for your reply. 
Thanks and sorry for my poor English.

**Comment by andreww** [comment]
The versions on my [web pages](http://homepages.see.leeds.ac.uk/~earawa/FoX/source/) correspond to the [tagged releases on github](https://github.com/andreww/fox/releases). Changes since the last release (2012-01-05) can be seen in the history of this repository ([see the commits here](https://github.com/andreww/fox/commits/master)). These include adding some basic tests for the SAX and DOM API (fuller SAX and DOM test suites exist [here](https://github.com/andreww/fox-sax-test) and [here](http://homepages.see.leeds.ac.uk/~earawa/software/FDOMTS-1.1.tgz)).

The releases on my web pages also include compact versions with tests and unneeded modules stripped out (as described in [this readme file](http://homepages.see.leeds.ac.uk/~earawa/FoX/source/Readme)). However, these don't include changes since early 2012, so this may be the reason why `len(attributes)` does not run.
