### ISSUE TITLE
Compilation error while linking fox_sax as a library

### ISSUE THREAD

**Issue by Socanal** [andreww/fox#61]
I am trying to make use of sax libraries in the oorb program [https://github.com/oorb/oorb](url) but I am strugling with it. After linking the libraries in the make file, and only adding the use statement to the program `USE FoX_sax` (not any functions or subroutines) While compiling, I am getting the next error, which repets itself over 20 times.

> ../main/oorb.f90:31:12:
>
> PROGRAM oorb
>            1
>Error: Fortran 2003: Procedure pointer at (1)

Adding the `USE` statement to the only subroutine which use FoX functions reports me the same error, just changing the file where it pops up. 

Maybe it is some problem with the linking of the library (which I will have to further investigate). It is difficult to explain the whole situation through here because it involve a quite complex Makefile, but I wanted to make sure if somebody faced this same issue before spending more time on it. 

Thank you very much!

**Comment by andreww** [comment]
I don't recall seeing that error (and it doesn't look like a very useful error either). My guess is that the FoX module files are not being found correctly at compile time (rather than a linking problem) but that is very much a guess. Does:
```
./configure
make
make check
```
work in the directory where you have downloaded FoX, using the same compiler?

If you've not already, take a look at [this documentation](http://homepages.see.leeds.ac.uk/~earawa/FoX/DoX/Embedding.html)  for some general suggestions on using FoX in an existing project.

**Comment by andreww** [comment]
I'm assuming this is fixed / worked around. Please reopen if not.
