### ISSUE TITLE
Conflicts with the foxf90 library https://gitlab.com/siesta-project/libraries/xmlf90

### ISSUE THREAD

**Issue by yurivict** [andreww/fox#80]
```
pkg-static: xmlf90-1.5.6 conflicts with fox-xml-4.1.2.91_5 (installs files into the same place).  Problematic file: /usr/local/include/m_dom_error.mod
```

**Comment by andreww** [comment]
This is likely because Siesta includes the full FoX distribution (or an earlier version thereof). The fix is to change the Siesta build to use a pre-installed version of FoX or to install it's copy into a different place. If this comes from a package manager (with access to both FoX and Siesta) then the same change could be implemented in those builds. A temporary fix would be to change the install location of FoX or Siesta. I don't think there is anything useful to change in FoX.
